# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-08-31 21:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('gymname', models.CharField(max_length=100, null=True)),
                ('country', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('zipcode', models.CharField(max_length=100)),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
                ('phonenumber', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=500)),
                ('contactperson', models.CharField(max_length=100)),
                ('blog', models.CharField(blank=True, max_length=200, null=True)),
                ('facebook', models.CharField(blank=True, max_length=200, null=True)),
                ('instagram', models.CharField(blank=True, max_length=200, null=True)),
                ('website', models.CharField(blank=True, max_length=100, null=True)),
                ('paybill', models.CharField(blank=True, max_length=100, null=True)),
                ('paymentcontactnumber', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'ordering': ('last_updated',),
            },
        ),
    ]
